namespace HalfSwordTweaker.Config;

public static class SettingsRegistry
{
    public static readonly Dictionary<string, List<SettingDefinition>> Tabs = new()
    {
        ["Display & Resolution"] = GetDisplayResolutionSettings(),
        ["Scalability Groups"] = GetScalabilityGroupsSettings()
    };

    private static List<SettingDefinition> GetDisplayResolutionSettings()
    {
        return new List<SettingDefinition>
        {
            SettingDefinition.Resolution(),
            SettingDefinition.Combo("FullscreenMode", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                new Dictionary<int, string> { [0] = "Fullscreen", [1] = "Borderless Windowed", [2] = "Windowed" },
                "1", "Display mode", PerformanceImpact.Low),
            SettingDefinition.Bool("bUseVSync", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                "1", "Vertical sync - reduces screen tearing but may lower FPS", PerformanceImpact.Low),
            SettingDefinition.Numeric("FrameRateLimit", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                0m, 360m, "0", "Framerate cap (0 = unlimited)", PerformanceImpact.Low, 0),
            SettingDefinition.Combo("r.AntiAliasingMethod", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [0] = "Off", [1] = "FXAA", [2] = "TAA", [4] = "TSR", [5] = "TSR[Kitch]" },
                "2", "Anti-aliasing method (TSR enables upscaling)", PerformanceImpact.Medium),
            SettingDefinition.TrackBarIntDependent("r.FXAA.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 5, "4", "FXAA quality (0=Console, 5=Ultra)", PerformanceImpact.Low, "r.AntiAliasingMethod", "1"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "2", "Temporal AA quality - controls input filtering", PerformanceImpact.Low, "r.AntiAliasingMethod", "2"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Quality_TSR", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "2", "Temporal AA quality - controls input filtering", PerformanceImpact.Low, "r.AntiAliasingMethod", "4"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Quality_TSRKitch", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "2", "Temporal AA quality - controls input filtering", PerformanceImpact.Low, "r.AntiAliasingMethod", "5"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Upsampling", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "1", "Temporal AA upsampling (0=Off, 1=On)", PerformanceImpact.Medium, "r.AntiAliasingMethod", "2"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Upsampling_TSR", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "1", "Temporal AA upsampling (0=Off, 1=On)", PerformanceImpact.Medium, "r.AntiAliasingMethod", "4"),
            SettingDefinition.TrackBarIntDependent("r.TemporalAA.Upsampling_TSRKitch", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "0", "Temporal AA upsampling (0=Off, 1=On)", PerformanceImpact.Medium, "r.AntiAliasingMethod", "5"),
            SettingDefinition.TrackBarIntDependent("r.TSR.Enable", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "1", "Temporal Super Resolution (0=Off, 1=On)", PerformanceImpact.Medium, "r.AntiAliasingMethod", "4"),
            SettingDefinition.TrackBarIntDependent("r.TSR.Enable_TSRKitch", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "1", "Temporal Super Resolution (0=Off, 1=On)", PerformanceImpact.Medium, "r.AntiAliasingMethod", "5"),
            SettingDefinition.TrackBarIntDependent("r.ScreenPercentage", "SystemSettings", ConfigSource.EngineIni,
                50, 200, "77", "Screen percentage for upscaling (lower = faster)", PerformanceImpact.High, "r.AntiAliasingMethod", "4"),
            SettingDefinition.TrackBarIntDependent("r.TSR.History.ScreenPercentage_TSRKitch", "SystemSettings", ConfigSource.EngineIni,
                50, 200, "100", "TSR history screen percentage", PerformanceImpact.Medium, "r.AntiAliasingMethod", "5"),
            SettingDefinition.TrackBarIntDependent("r.ScreenPercentage_TSRKitch", "SystemSettings", ConfigSource.EngineIni,
                50, 200, "100", "Screen percentage for upscaling (lower = faster)", PerformanceImpact.High, "r.AntiAliasingMethod", "5"),
            SettingDefinition.Bool("bUseDynamicResolution", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                "0", "Dynamically scale resolution to maintain framerate", PerformanceImpact.Medium),
            SettingDefinition.Bool("bUseHDRDisplayOutput", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                "0", "Enable HDR display output", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("HDRDisplayOutputNits", "/Script/Engine.GameUserSettings", ConfigSource.GameUserSettings,
                100, 2000, "1000", "HDR brightness in nits", PerformanceImpact.Low),
            SettingDefinition.Bool("bEnableMouseSmoothing", "/Script/Engine.InputSettings", ConfigSource.GameUserSettings,
                "0", "Enable mouse smoothing (may affect input latency)", PerformanceImpact.Low),
            SettingDefinition.StringCombo("PreferredRHI", "D3DRHIPreference", ConfigSource.GameUserSettings,
                new Dictionary<string, string> { ["dx11"] = "DirectX 11", ["dx12"] = "DirectX 12", ["vulkan"] = "Vulkan" },
                "dx12", "Rendering hardware interface (requires restart)", PerformanceImpact.Low)
        };
    }

    private static List<SettingDefinition> GetScalabilityGroupsSettings()
    {
        return new List<SettingDefinition>
        {
            SettingDefinition.TrackBarInt("sg.ResolutionQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 100, "100", "Resolution quality", PerformanceImpact.High),
            SettingDefinition.TrackBarInt("sg.ViewDistanceQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "View distance quality", PerformanceImpact.High),
            SettingDefinition.TrackBarInt("sg.AntiAliasingQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Anti-aliasing quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.ShadowQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Shadow quality", PerformanceImpact.High),
            SettingDefinition.TrackBarInt("sg.GlobalIlluminationQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Global illumination quality", PerformanceImpact.Epic),
            SettingDefinition.TrackBarInt("sg.ReflectionQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Reflection quality", PerformanceImpact.Epic),
            SettingDefinition.TrackBarInt("sg.PostProcessQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Post-processing quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.TextureQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Texture quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.EffectsQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Effects quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.FoliageQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Foliage quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.ShadingQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Shading quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("sg.LandscapeQuality", "ScalabilityGroups", ConfigSource.ScalabilityGroups,
                0, 4, "3", "Landscape quality", PerformanceImpact.Medium)
        };
    }

    private static List<SettingDefinition> GetAdvancedSettings()
    {
        return new List<SettingDefinition>
        {
            // Anti-Aliasing & Textures (9)
            SettingDefinition.TrackBarInt("r.ScreenPercentage", "SystemSettings", ConfigSource.EngineIni,
                10, 200, "100", "Internal render resolution percentage", PerformanceImpact.High),
            SettingDefinition.Bool("r.TSR.Enable", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable Temporal Super Resolution upscaler", PerformanceImpact.Medium),
            SettingDefinition.Bool("r.TemporalAA.Upsampling", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable temporal anti-aliasing upsampling", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.PostProcessAAQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 6, "3", "Post-process anti-aliasing quality", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.MaxAnisotropy", "SystemSettings", ConfigSource.EngineIni,
                0, 16, "8", "Anisotropic filtering level (sharper textures at angles)", PerformanceImpact.Low),
            SettingDefinition.Bool("r.TextureStreaming", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable texture streaming", PerformanceImpact.Low),
            SettingDefinition.Bool("r.Streaming.LimitPoolSizeToVRAM", "SystemSettings", ConfigSource.EngineIni,
                "1", "Limit texture pool to available VRAM", PerformanceImpact.Low),
            SettingDefinition.Numeric("r.Streaming.MipBias", "SystemSettings", ConfigSource.EngineIni,
                -2.0m, 2.5m, "0.0", "Texture mip-map bias (negative = sharper, positive = blurrier)", PerformanceImpact.Low, 1),
            
            // Post-Processing (11)
            SettingDefinition.TrackBarInt("r.AmbientOcclusionLevels", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "1", "Ambient occlusion quality levels", PerformanceImpact.Medium),
            SettingDefinition.Numeric("r.AmbientOcclusionRadiusScale", "SystemSettings", ConfigSource.EngineIni,
                0.5m, 2.0m, "1.0", "Ambient occlusion radius scale", PerformanceImpact.Low, 1),
            SettingDefinition.TrackBarInt("r.DepthOfFieldQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "0", "Depth of field quality (0 = off)", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.MotionBlurQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 4, "3", "Motion blur quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.Bool("r.Tonemapper.GrainQuantization", "SystemSettings", ConfigSource.EngineIni,
                "1", "Film grain quantization (reduces color banding)", PerformanceImpact.Low),
            SettingDefinition.Numeric("r.Tonemapper.Sharpen", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 2.0m, "0.0", "Image sharpening strength", PerformanceImpact.Low, 1),
            SettingDefinition.TrackBarInt("r.LensFlareQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "0", "Lens flare quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("r.SceneColorFringeQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "0", "Chromatic aberration quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("r.EyeAdaptationQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 2, "0", "Auto-exposure/eye adaptation quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.Bool("r.SeparateTranslucency", "SystemSettings", ConfigSource.EngineIni,
                "1", "Use separate translucency pass for better sorting", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.TranslucencyLightingVolumeDim", "SystemSettings", ConfigSource.EngineIni,
                4, 64, "24", "Translucency lighting volume dimensions", PerformanceImpact.Medium),
            
            // Shadows (14)
            SettingDefinition.TrackBarInt("r.ShadowQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 5, "5", "Overall shadow quality", PerformanceImpact.High),
            SettingDefinition.Combo("r.Shadow.MaxResolution", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [256] = "256", [512] = "512", [1024] = "1024", [2048] = "2048", [4096] = "4096" },
                "1024", "Maximum shadow map resolution", PerformanceImpact.High),
            SettingDefinition.Combo("r.Shadow.MaxCSMResolution", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [256] = "256", [512] = "512", [1024] = "1024", [2048] = "2048", [4096] = "4096" },
                "1024", "Cascaded shadow map maximum resolution", PerformanceImpact.High),
            SettingDefinition.TrackBarInt("r.Shadow.CSM.MaxCascades", "SystemSettings", ConfigSource.EngineIni,
                1, 4, "4", "Number of cascaded shadow map cascades", PerformanceImpact.High),
            SettingDefinition.Numeric("r.Shadow.DistanceScale", "SystemSettings", ConfigSource.EngineIni,
                0.5m, 3.0m, "1.0", "Shadow draw distance scale", PerformanceImpact.Medium, 1),
            SettingDefinition.Numeric("r.Shadow.TransitionScale", "SystemSettings", ConfigSource.EngineIni,
                0.5m, 3.0m, "1.0", "Shadow fade transition scale", PerformanceImpact.Low, 1),
            SettingDefinition.Bool("r.ContactShadows", "SystemSettings", ConfigSource.EngineIni,
                "0", "Screen-space contact shadows (adds detail near surfaces)", PerformanceImpact.Medium),
            SettingDefinition.Bool("r.DistanceFieldShadowing", "SystemSettings", ConfigSource.EngineIni,
                "1", "Distance field shadows (soft shadows from distant objects)", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.LightShaftQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 1, "1", "Light shaft/god rays quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.Bool("r.Shadow.Virtual.Enable", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable virtual shadow maps (high quality shadows)", PerformanceImpact.High),
            SettingDefinition.Bool("r.CapsuleShadows", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable capsule shadows for characters", PerformanceImpact.Medium),
            SettingDefinition.Bool("r.CapsuleDirectShadows", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable capsule direct shadows from movable lights", PerformanceImpact.Medium),
            SettingDefinition.Bool("r.CapsuleIndirectShadows", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable capsule indirect shadows from precomputed lighting", PerformanceImpact.Medium),
            SettingDefinition.Bool("r.AllowLandscapeShadows", "SystemSettings", ConfigSource.EngineIni,
                "1", "Allow shadows from landscape terrain", PerformanceImpact.Low),
            
            // Global Illumination (9)
            SettingDefinition.Bool("r.Lumen.GlobalIllumination", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable Lumen global illumination (dynamic GI)", PerformanceImpact.Epic),
            SettingDefinition.Bool("r.Lumen.Reflections", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable Lumen reflections (dynamic reflections)", PerformanceImpact.Epic),
            SettingDefinition.Numeric("r.Lumen.Reflections.MaxRoughnessToTrace", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 1.0m, "0.4", "Maximum surface roughness to trace reflections (higher = more surfaces)", PerformanceImpact.High, 1),
            SettingDefinition.TrackBarInt("r.Lumen.Reflections.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 4, "1", "Lumen reflections quality", PerformanceImpact.High),
            SettingDefinition.Bool("r.Lumen.HardwareRayTracing", "SystemSettings", ConfigSource.EngineIni,
                "0", "Use hardware ray tracing for Lumen (requires RT-capable GPU)", PerformanceImpact.Epic),
            SettingDefinition.TrackBarInt("r.SSR.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 4, "3", "Screen-space reflections quality (0 = off)", PerformanceImpact.Medium),
            SettingDefinition.Numeric("r.SSR.MaxRoughness", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 1.0m, "0.8", "Maximum roughness for screen-space reflections", PerformanceImpact.Medium, 1),
            SettingDefinition.Combo("r.DynamicGlobalIlluminationMethod", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [0] = "None", [1] = "Lumen", [2] = "SSGI" },
                "1", "Dynamic global illumination method", PerformanceImpact.Epic),
            SettingDefinition.Combo("r.ReflectionMethod", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [0] = "None", [1] = "Lumen", [2] = "Screen Space" },
                "1", "Reflection rendering method", PerformanceImpact.Epic),
            
            // Ray Tracing (6)
            SettingDefinition.Bool("r.RayTracing", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable ray tracing (requires RT-capable GPU)", PerformanceImpact.Epic),
            SettingDefinition.Bool("r.RayTracing.GlobalIllumination", "SystemSettings", ConfigSource.EngineIni,
                "0", "Ray traced global illumination", PerformanceImpact.Epic),
            SettingDefinition.Bool("r.RayTracing.Reflections", "SystemSettings", ConfigSource.EngineIni,
                "0", "Ray traced reflections", PerformanceImpact.Epic),
            SettingDefinition.Bool("r.RayTracing.Shadows", "SystemSettings", ConfigSource.EngineIni,
                "0", "Ray traced shadows", PerformanceImpact.Epic),
            SettingDefinition.Bool("r.RayTracing.AmbientOcclusion", "SystemSettings", ConfigSource.EngineIni,
                "0", "Ray traced ambient occlusion", PerformanceImpact.High),
            SettingDefinition.Bool("r.PathTracing", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable path tracing (requires RT-capable GPU, very expensive)", PerformanceImpact.Epic),
            
            // Geometry & Foliage (6)
            SettingDefinition.Numeric("r.StaticMeshLODDistanceScale", "SystemSettings", ConfigSource.EngineIni,
                0.1m, 10.0m, "1.0", "Static mesh LOD distance scale (lower = higher detail)", PerformanceImpact.Medium, 1),
            SettingDefinition.TrackBarInt("r.SkeletalMeshLODBias", "SystemSettings", ConfigSource.EngineIni,
                -4, 4, "0", "Skeletal mesh LOD bias (negative = higher detail)", PerformanceImpact.Medium),
            SettingDefinition.Numeric("foliage.DensityScale", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 1.0m, "1.0", "Foliage density (0 = no foliage, 1 = full density)", PerformanceImpact.Medium, 1),
            SettingDefinition.Numeric("foliage.LODDistanceScale", "SystemSettings", ConfigSource.EngineIni,
                0.1m, 10.0m, "1.0", "Foliage LOD distance scale", PerformanceImpact.Medium, 1),
            SettingDefinition.Bool("grass.Enable", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable grass rendering", PerformanceImpact.Medium),
            SettingDefinition.Numeric("grass.DensityScale", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 1.0m, "1.0", "Grass density scale (0 = no grass, 1 = full density)", PerformanceImpact.Medium, 1),
            
            // View Distance & Effects (15)
            SettingDefinition.Numeric("r.ViewDistanceScale", "SystemSettings", ConfigSource.EngineIni,
                0.1m, 10.0m, "1.0", "Global view distance scale", PerformanceImpact.High, 1),
            SettingDefinition.TrackBarInt("r.SSS.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "3", "Subsurface scattering quality (skin, wax, etc.)", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("r.BloomQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 4, "4", "Bloom quality (0 = off)", PerformanceImpact.Low),
            SettingDefinition.Bool("r.Fog", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable fog effects", PerformanceImpact.Low),
            SettingDefinition.Bool("r.VolumetricFog", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable volumetric fog (ray-marched fog)", PerformanceImpact.High),
            SettingDefinition.Bool("r.VolumetricCloud", "SystemSettings", ConfigSource.EngineIni,
                "1", "Enable volumetric clouds", PerformanceImpact.High),
            SettingDefinition.Combo("r.DetailMode", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [0] = "Low", [1] = "Medium", [2] = "High" },
                "2", "Overall detail mode (affects actor rendering)", PerformanceImpact.High),
            SettingDefinition.Combo("r.MaterialQualityLevel", "SystemSettings", ConfigSource.EngineIni,
                new Dictionary<int, string> { [0] = "Low", [1] = "Medium", [2] = "High", [3] = "Epic" },
                "3", "Material quality level (affects shader complexity)", PerformanceImpact.Medium),
            SettingDefinition.TrackBarInt("r.SkyLightingQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 2, "1", "Sky lighting quality", PerformanceImpact.Medium),
            SettingDefinition.Numeric("r.SkylightIntensityMultiplier", "SystemSettings", ConfigSource.EngineIni,
                0.1m, 2.0m, "1.0", "Skylight intensity multiplier", PerformanceImpact.Low, 1),
            SettingDefinition.TrackBarInt("r.LightFunctionQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 2, "2", "Light function quality", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("r.RefractionQuality", "SystemSettings", ConfigSource.EngineIni,
                0, 3, "3", "Refraction quality (glass, water, etc.)", PerformanceImpact.Low),
            SettingDefinition.TrackBarInt("r.Upscale.Quality", "SystemSettings", ConfigSource.EngineIni,
                0, 4, "3", "Upscaling quality", PerformanceImpact.Medium),
            SettingDefinition.Numeric("r.EmitterSpawnRateScale", "SystemSettings", ConfigSource.EngineIni,
                0.0m, 1.0m, "1.0", "Particle emitter spawn rate scale (lower = fewer particles)", PerformanceImpact.Medium, 1),
            SettingDefinition.Bool("r.DistanceFieldAO", "SystemSettings", ConfigSource.EngineIni,
                "0", "Enable distance field ambient occlusion", PerformanceImpact.Medium)
        };
    }
}
